# Generated by Django 3.2.4 on 2021-06-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='order_count',
            new_name='count_order',
        ),
    ]
